// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCybXRJKquwz8fvw8j6cMA5xvrmWTeYQhI',
    appId: '1:172501748066:web:02172c0a582c08fe2c843b',
    messagingSenderId: '172501748066',
    projectId: 'note-app-b808d',
    authDomain: 'note-app-b808d.firebaseapp.com',
    databaseURL: 'https://note-app-b808d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'note-app-b808d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5eSAXcL9uMBJocavIBGEiwm7Yo0P0-aE',
    appId: '1:172501748066:android:9c647fbf34d4583e2c843b',
    messagingSenderId: '172501748066',
    projectId: 'note-app-b808d',
    databaseURL: 'https://note-app-b808d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'note-app-b808d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0NzDQW3I_qefjoz0f91KEzQxCIR3k5wo',
    appId: '1:172501748066:ios:fbf0445f56bcb8392c843b',
    messagingSenderId: '172501748066',
    projectId: 'note-app-b808d',
    databaseURL: 'https://note-app-b808d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'note-app-b808d.appspot.com',
    iosClientId: '172501748066-q51j4pef9fvnq3457rahd02hmoli4ui5.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0NzDQW3I_qefjoz0f91KEzQxCIR3k5wo',
    appId: '1:172501748066:ios:fbf0445f56bcb8392c843b',
    messagingSenderId: '172501748066',
    projectId: 'note-app-b808d',
    databaseURL: 'https://note-app-b808d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'note-app-b808d.appspot.com',
    iosClientId: '172501748066-q51j4pef9fvnq3457rahd02hmoli4ui5.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );
}
